# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddaa68d46e40b56cfc67df8a3fc75f8d187978881699156c9504d9106b88e0b936aae996be23b54b590928445c501c7af9a41705ce7bdb92f5bda0178e0aeb03

test:
  secret_key_base: 527b6fd181a776f50a2ec9fb558df0c43fd8b8118188c7d5041ead50e67b19394aec02b1e584dab9ef826d61665807914b6c89095be5acf72cd5550e528bfa3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
